In [23]:
%load_ext autoreload
%autoreload 3

import gconcord as cc
import numpy as np

# import importlib
# importlib.reload(cc)

# true precision matrix
omega = np.zeros((3,3), order="C")
omega[0, 1] = 2.1
omega[1, 2] = -2.1
omega += omega.T
np.fill_diagonal(omega, 3)

# true covariance matrix
sigma = np.linalg.inv(omega)

# observations
data = np.random.multivariate_normal([0]*3, sigma, 500)

# sample covariance matrix
S = np.cov(data, rowvar=False)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [34]:
# omega_hat, hist = cc.pyccista(S, 0.5, maxitr=1000)
omega_hat, hist = cc.pyccista(S, 0.5, maxitr=1000)
print("omega_hat:\n %s\n" % (str(omega_hat)))
print("hist: (inner_iter_count, delta_subg, objective)\n %s\n" % (str(hist[-3:])))
print("iterations: %d" % (len(hist)))
print("relative subg norm: %e" % (hist[-1,1]))
print("objective: %e" % (hist[-1,2]))

omega_hat:
 [[ 1.16599714  0.78771182  0.        ]
 [ 0.78771182  1.15357733 -0.78199937]
 [ 0.         -0.78199937  1.16650021]]

hist: (inner_iter_count, delta_subg, objective)
 [[0.00000000e+00 2.54291302e-05 1.83438637e+00]
 [5.00000000e+00 1.24204357e-05 1.83438637e+00]
 [4.00000000e+00 5.57716100e-06 1.83438637e+00]]

iterations: 77
relative subg norm: 5.577161e-06
objective: 1.834386e+00


In [14]:
sigii = np.diag(omega_hat.diagonal())
np.matmul(np.matmul(np.sqrt(sigii), omega_hat), np.sqrt(sigii))

array([[ 2.68086761,  1.74531533,  0.11903631],
       [ 1.74531533,  2.47455082, -1.77869446],
       [ 0.11903631, -1.77869446,  2.74703368]])

In [16]:
np.linalg.inv(S)

array([[ 3.14093935,  2.04766398,  0.2159001 ],
       [ 2.04766398,  2.96450268, -2.09585525],
       [ 0.2159001 , -2.09585525,  3.21037287]])

In [17]:
omega

array([[ 3. ,  2.1,  0. ],
       [ 2.1,  3. , -2.1],
       [ 0. , -2.1,  3. ]])

In [1]:
%load_ext autoreload
%autoreload 2

import gconcord as cc
import numpy as np

# import importlib
# importlib.reload(cc)

# true precision matrix
omega = np.zeros((3,3), order="C")
omega[0, 1] = 2.1
omega[1, 2] = -2.1
omega += omega.T
np.fill_diagonal(omega, 3)

# true covariance matrix
sigma = np.linalg.inv(omega)

# observations
data = np.random.multivariate_normal([0]*3, sigma, 500)

# sample covariance matrix
S = np.cov(data, rowvar=False)

ModuleNotFoundError: No module named 'gconcord'

In [2]:
cc.ccista(S, 0.5, maxitr=1000).todense()

NameError: name 'cc' is not defined